FROM python:3.8.3

WORKDIR /home/Desktop/mendicantbias

COPY . /home/Desktop/mendicantbias

RUN pip install -U pip
RUN pip install -r requirements.txt

ENTRYPOINT ["bash","docker_entrypoint.sh"]

CMD python3 main.py
